  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: documentportaltd
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: document-portal-container
          Image: !Ref ImageUrl
          PortMappings:
            - ContainerPort: 8080
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/documentportal
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: ENV
              Value: production
            - Name: LOG_LEVEL
              Value: info
          Secrets:                              # <-- add this section
            - Name: GROQ_API_KEY
              ValueFrom: arn:aws:secretsmanager:us-east-1:719742385994:secret:docportal/groq-api-key-XXXXX
            - Name: GOOGLE_API_KEY
              ValueFrom: arn:aws:secretsmanager:us-east-1:719742385994:secret:docportal/google-api-key-YYYYY
